apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-app-config-prod # Nombre específico para PROD
  namespace: calcu-streamlit-app
data:
# Configuración del backend
  backend-environment: "production"
  backend-log-level: "WARNING"
  backend-port: "8000"         # El pod sigue usando este
  
  # Configuración del frontend
  frontend-port: "8501"        # El pod sigue usando este
  frontend-server-address: "0.0.0.0"
  streamlit-theme-base: "dark"
  
  # URLs de servicios INTERNAS (DNS de Kubernetes)
  # IMPORTANTE: Ahora apuntamos al puerto 80 del Service
  #backend-service-url: "http://backend-service" 
  backend-service-url: "http://192.168.0.227/api"
  frontend-service-url: "http://frontend-service"